annotations:
  paths:
    - data/full_set_all_models_processed.csv

targets:
  dataset_name: ucberkeley-dlab/measuring-hate-speech
  split: train
  min_annotators: 4
  agreement_threshold: 0.75
  min_comments_per_target: 50
  anchor_targets: true
  collapse:
    target_origin_specific_country: target_origin
    target_origin_immigrant: target_origin
    target_origin_migrant_worker: target_origin
    target_origin_undocumented: target_origin
    target_origin_other: target_origin
    target_gender_transgender_women: target_gender_transgender
    target_gender_transgender_men: target_gender_transgender
    target_gender_transgender_unspecified: target_gender_transgender
  exclude:
    - target_religion_other
    - target_race_other
    - target_sexuality_other
    - target_race_native_american
    - target_religion_mormon

anchors:
  comment_scores_path: facets/human_baseline/human_facets_scores.1.txt
  item_scores_path: facets/human_baseline/human_facets_scores.3.txt

output:
  facets_run_dir: facets/full_set_all_models_target_drf_free_judges
  target_labels_path: data/full_set_all_models_target_drf_free_judges_labels.csv
  facets_data_filename: full_set_all_models_target_drf_free_judges_data.tsv
  facets_spec_filename: full_set_all_models_target_drf_free_judges_spec.txt
  facets_score_filename: full_set_all_models_target_drf_free_judges_scores.txt
  facets_output_filename: full_set_all_models_target_drf_free_judges_output.txt

facets:
  title: MHS Full Set All Models Target-Identity DRF Free Judges
  model: "?, ?B, #, ?B, R"
  noncenter: 2
  positive: 1
  arrange: N
  subset_detection: No
  delements:
    - 1N
    - 2N
    - 3N
    - 4N
  bias: Difficulty
  zscore: "0, 0"
  csv: Tab
