annotations:
  paths:
    - data/full_run_models_reference_set_processed.csv

anchors:
  comment_scores_path: facets/human_baseline/human_facets_scores.1.txt
  item_scores_path: facets/human_baseline/human_facets_scores.3.txt

output:
  facets_run_dir: facets/full_run_models_reference_set_severity_decomposition
  facets_data_filename: full_run_models_reference_set_severity_decomposition_data.tsv
  facets_spec_filename: full_run_models_reference_set_severity_decomposition_spec.txt
  facets_score_filename: full_run_models_reference_set_severity_decomposition_scores.txt
  facets_output_filename: full_run_models_reference_set_severity_decomposition_output.txt

facets:
  title: MHS Full-Run Models Reference Set Item-Dependent Severity Decomposition
  model: "?, ?B, #B, R"
  noncenter: 2
  positive: 1
  arrange: N
  subset_detection: No
  delements:
    - 1N
    - 2N
    - 3N
  bias: Difficulty
  zscore: "0, 0"
  csv: Tab
