annotations:
  paths:
    - data/full_set_all_models_no_minimax_processed.csv

scoring:
  response_recodes:
    insult:
      0: 0
      1: 0
      2: 0
      3: 1
      4: 2
    humiliate:
      0: 0
      1: 0
      2: 0
      3: 1
      4: 2
    status:
      0: 0
      1: 0
      2: 0
      3: 1
      4: 2
    dehumanize:
      0: 0
      1: 0
      2: 0
      3: 1
      4: 2
    violence:
      0: 0
      1: 0
      2: 0
      3: 1
      4: 1
    genocide:
      0: 0
      1: 0
      2: 0
      3: 1
      4: 1
    hate_speech:
      0: 0
      1: 0
      2: 1

output:
  facets_run_dir: facets/full_set_all_models_llm_only_no_minimax_llm_recoded
  facets_data_filename: full_set_all_models_llm_only_no_minimax_llm_recoded_data.tsv
  facets_spec_filename: full_set_all_models_llm_only_no_minimax_llm_recoded_spec.txt
  facets_score_filename: full_set_all_models_llm_only_no_minimax_llm_recoded_scores.txt
  facets_output_filename: full_set_all_models_llm_only_no_minimax_llm_recoded_output.txt

facets:
  title: MHS Full Set All Models LLM-Only No-MiniMax LLM-Recoded Scale
  model: "?, ?, #, R"
  noncenter: 1
  positive: 1
  arrange: N
  subset_detection: No
  delements:
    - 1N
    - 2N
    - 3N
  csv: Tab
